version: '3'
tasks:
    init:
        desc: Init terraform
        dir: deploy/terraform
        cmds:
            - terraform init

    plan:
        desc: 'Show planned terraform changes'
        dir: deploy/terraform
        cmds:
            - terraform plan -var-file secrets.tfvars

    apply:
        desc: 'Apply terraform changes'
        dir: deploy/terraform
        cmds:
            - terraform apply -var-file secrets.tfvars

    output:
        desc: 'Print terraform output'
        dir: deploy/terraform
        cmds:
            - terraform output

    import:
        desc: "Import resource"
        dir: deploy/terraform
        cmds:
            - terraform import -var-file secrets.tfvars {{ .CLI_ARGS }}
