# Application settings
app_domain: CHANGEME
app_docker_image: "{{ lookup('env', 'APP_DOCKER_IMAGE')|mandatory }}"
app_languages: [en, ru]
project_slug: {{ cookiecutter.project_name }}
acme_email: CHANGEME
github_username: alex.oleshkevich
github_token: "{{ vault_github_token }}"
secret_key: "{{ vault_secret_key }}"
google_oauth_client_secret: "{{ vault_google_oauth_client_secret }}"
aws_secret_access_key: "{{ vault_aws_secret_access_key }}"

# deployment
app_replicas: 1
celery_worker_replicas: 1

# database settings
database_name: {{ cookiecutter.project_name }}
database_user: {{ cookiecutter.project_name }}
database_host: postgresql
database_pass: "{{ vault_database_pass }}"
database_url: "postgresql+asyncpg://{{ database_user }}:{{ database_pass }}@{{ database_host }}/{{ database_name}}"

# credentials to the database instance
database_instance_user: app
database_instance_pass: "{{ vault_database_instance_pass }}"
database_instance_host: 127.0.0.1

# email settings
email_url: "{{ vault_email_url }}"
email_from_name: "Takinada.io"
email_from_address: "support@{{cookiecutter.project_name}}.io"

# security settings
trusted_hosts: ["{{cookiecutter.project_name}}.io"]

# redis
redis_image: "redis:6"
redis_url: "{{ vault_redis_url }}"

# sentry
sentry_url: "{{ vault_sentry_url }}"
traces_sample_rate: 0.1

# map vault secrets to docker swarm secrets
secrets:
 - { name: database_url, value: "{{ database_url }}" }
 - { name: email_url, value: "{{ email_url }}" }
 - { name: sentry_url, value: "{{ sentry_url }}" }
 - { name: aws_secret_access_key, value: "{{ aws_secret_access_key }}" }
 - { name: redis_url, value: "{{ redis_url }}" }
 - { name: secret_key, value: "{{ secret_key }}" }
 - { name: google_oauth_client_secret, value: "{{ google_oauth_client_secret }}" }

# environment variables for docker
envvars:
    APP_DEBUG: "0"
    APP_APP_NAME: "Takinada"
    APP_BASE_URL: "https://{{ app_domain }}"
    APP_ENV: "production"
    APP_LOCALIZATION__LANGUAGE: "en"
    APP_LOCALIZATION__TIMEZONE: "Europe/Minsk"
    APP_STORAGE_UPLOADS_AWS_ACCESS_KEY: "AKIAYV7LQZ4YS6VKHL6A"
    APP_MAIL__FROM_NAME: "{{ email_from_name }}"
    APP_MAIL__FROM_EMAIL: "{{ email_from_address }}"
    APP_SENTRY__TRACES_SAMPLE_RATE: "{{ traces_sample_rate }}"
    APP_STORAGES__DEFAULT: s3
    LOG_LEVEL: debug

#    APP_LOCALIZATION__LANGUAGES: "{{ app_languages|to_json }}"
#    APP_SECURITY__TRUSTED_HOSTS: "{{ trusted_hosts|to_json }}"
