-   name: Install required PIP packages
    pip:
        name: jsondiff

-   name: Authenticate Github Docker registry
    docker_login:
        registry: ghcr.io
        username: "{{ github_username }}"
        password: "{{ github_token }}"

-   name: Create PostgreSQL database
    postgresql_db:
        name: "{{ database_name }}"
        login_host: "{{ database_instance_host }}"
        login_user: "{{ database_instance_user }}"
        login_password: "{{ database_instance_pass }}"

-   name: Create PostgreSQL database user
    postgresql_user:
        name: "{{ database_user }}"
        password: "{{ database_pass }}"
        db: "{{ database_name }}"
        login_host: "{{ database_instance_host }}"
        login_user: "{{ database_instance_user }}"
        login_password: "{{ database_instance_pass }}"

-   name: Create application secrets
    docker_secret:
        name: "{{ project_slug }}.{{ item.name }}"
        data: "{{ item.value }}"
        rolling_versions: yes
    no_log: true
    with_items: "{{ secrets }}"
    register: registered_secrets

-   name: Create Docker stack for application from "{{ app_docker_image }}"
    docker_stack:
        name: "{{ project_slug }}"
        prune: yes
        with_registry_auth: yes
        compose:
            - "{{ lookup('template', 'docker-compose.yml.j2') | from_yaml }}"
        state: present
