name: "Setup Ansible"
inputs:
    ssh_private_key:
        required: true
    vault_password:
        required: true
    hosts:
        required: true
runs:
    using: "composite"
    steps:
          - name: Set up Python
            uses: actions/setup-python@v4
            with:
                python-version: '3.10'

          -   name: Cache packages
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cache/pip
                  key: ${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

          - name: Install SSH key
            uses: shimataro/ssh-key-action@v2
            with:
                key: ${{ inputs.ssh_private_key }}
                name: id_rsa # optional
                known_hosts: ${{ inputs.hosts }}
                if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)

          - name: Install packages
            shell: bash
            run: |
              python -m pip install --upgrade pip
              pip install ansible

          - name: Export vault password
            env:
                ANSIBLE_VAULT_PASSWORD: '${{ inputs.vault_password }}'
            shell: bash
            run: |
              echo "#!/bin/bash" > ~/vault.pass
              echo "echo $ANSIBLE_VAULT_PASSWORD" >> ~/vault.pass
              chmod +x ~/vault.pass
